# Generated by Django 3.2.7 on 2021-09-08 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DatasetModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=255)),
                ('categories', models.CharField(blank=True, default='', max_length=5000)),
                ('images_path', models.CharField(default='', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ImageModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('filename', models.CharField(default='', max_length=255)),
                ('img_url', models.CharField(default='', max_length=500)),
            ],
        ),
    ]
