# Generated by Django 3.2.7 on 2021-09-08 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visualization', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagemodel',
            name='dataset',
            field=models.ManyToManyField(to='visualization.DatasetModel'),
        ),
        migrations.AddField(
            model_name='imagemodel',
            name='europeana_id',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='imagemodel',
            name='uri',
            field=models.CharField(default='', max_length=500),
        ),
    ]
